apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: acr-pull-secret
  namespace: gitops
  labels:
    app: pfe-gitops-demo
    env: dev
data:
  .dockerconfigjson: eyJhdXRocyI6eyJwZmVnaXRvcHNhY3IuYXp1cmVjci5pbyI6eyJ1c2VybmFtZSI6InBmZUdpdE9wc0FjciIsInBhc3N3b3JkIjoiSy9lRGxtT1dQOHhJNEFOL1haPTJRNVVwZDlYRjBtUlciLCJhdXRoIjoiY0dabFIybDBUM0J6UVdOeU9rc3ZaVVJzYlU5WFVEaDRTVFJCVGk5WVdqMHlVVFZWY0dRNVdFWXdiVkpYIn19fQ==
