apiVersion: v1
kind: ConfigMap
metadata:
  name: pfe-app-config
  namespace: gitops
  labels:
    app: pfe-gitops-demo
    env: dev
  annotations:
    app: pfe-gitops-demo
    env: dev
data:
  application.yaml: |-
    server:
      servlet:
        context-path: /app
      port: '8080'
    management:
      endpoints:
        web:
          exposure:
            include: health,info,prometheus
            exclude: ''
        jmx:
          exposure:
            include: '*'
            exclude: ''
      endpoint:
        health:
          probes:
            enabled: 'true'
          show-details: always
    info:
      git:
        enabled: true
        mode: full
    spring:
      application:
        name: "pfe-gitops-demo"
      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: 'true'
        hibernate:
          ddl-auto: update
      datasource:
        password: ${MYSQL_ROOT_PASSWORD}
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DB}?useUnicode=true&characterEncoding=UTF-8
    logging:
      file:
        name: logs/pfe-gitops-demo.log
      level:
        org:
          springframework: 
            web:
              servlet:
                DispatcherServlet: DEBUG
        com:
          zaxxer:
            hikari: warn
        root: INFO
      pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} - %-5level - %logger{60} - %msg%n'