apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: gitops
  labels:
    app: pfe-gitops-demo
    env: dev
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS timesheet_db;