apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pfe-gitops-db-data
  namespace: gitops
  labels:
    app: pfe-gitops-demo
    env: dev
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  