apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: kube-prometheus-stack-alertmanager-config
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: alertmanager-config
    meta.helm.sh/release-namespace: monitoring
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 35.3.1
    chart: kube-prometheus-stack-35.3.1
    heritage: Helm
    release: kube-prometheus-stack
  annotations:
    meta.helm.sh/release-name: kube-prometheus-stack
    meta.helm.sh/release-namespace: monitoring
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: alertmanager-config
    meta.helm.sh/release-namespace: monitoring
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 35.3.1
    chart: kube-prometheus-stack-35.3.1
    heritage: Helm
    release: kube-prometheus-stack
spec:
  inhibitRules: []
  route:
    receiver: "default"
    groupBy: ['job', 'alertname']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 15m
    routes:
      - receiver: deadmansswitch
        groupBy: 
          - alertname
        match_re: 
          alertname: DeadMansSwitch|KuredReplicasMismatch|KuredPodNotReady|InfoInhibitor|Watchdog
        repeatInterval: 10m
      - receiver: email-alerts
        match_re:
          severity: warning|major|critical
        repeatInterval: 10m
        continue: true
  receivers:
    - name: default
    - name: deadmansswitch
    - name: email-alerts
      emailConfigs:
        - sendResolved: true
          smarthost: smtp.gmail.com:587
          requireTLS: true
          authUsername: ahmedfourat.touzri@esprit.tn
          authPassword:
            name: alertmanager-smtp-auth
            key: PFE_SMTP_PASSWORD
          to: ahmedfourat.touzri@esprit.tn
          from: pfe-gitops-devsecops@azure.cloud 
          