name: "Test workflow"

on:
  workflow_dispatch:
    

jobs:
  test-job:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      packages: write
      security-events: write
  
    name: "Test job"

    steps:
      - name: "Checkout Git repo"
        uses: actions/checkout@v3

      - name: "echo variable"
        run: |
          echo ${{ secrets.DEPLOY_GITHUB_TOKEN }}